const js = require("@eslint/js");
const stylistic = require("@stylistic/eslint-plugin");

module.exports = [
  js.configs.recommended,
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        global: "readonly",
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        // Arras-specific globals
        util: "writable",
        Config: "writable",
        servers: "writable",
        onServerLoaded: "writable",
        performance: "writable",
        Bun: "writable",
        Class: "writable",
        definitionCombiner: "writable",
        ensureIsClass: "writable",
        Vector: "writable",
        lazyRealSizes: "writable",
        mockupData: "writable",
        Tile: "writable",
        gameManager: "writable",
        Events: "writable",
        ran: "writable",
        protocol: "writable",
        mazeGenerator: "writable",
        grid: "writable",
        cannotRespawn: "writable",
        entities: "writable",
        targetableEntities: "writable",
        unspawnableTeam: "writable",
        walls: "writable",
        entitiesToAvoid: "writable",
        chats: "writable",
        travellingPlayers: "writable",
        fps: "writable",
        loadedAddons: "writable",
        TEAM_BLUE: "writable",
        TEAM_GREEN: "writable",
        TEAM_RED: "writable",
        TEAM_PURPLE: "writable",
        TEAM_YELLOW: "writable",
        TEAM_ORANGE: "writable",
        TEAM_BROWN: "writable",
        TEAM_CYAN: "writable",
        TEAM_DREADNOUGHTS: "writable",
        TEAM_ROOM: "writable",
        TEAM_ENEMIES: "writable",
        getSpawnableArea: "writable",
        teamNames: "writable",
        teamColors: "writable",
        getTeamName: "writable",
        getTeamColor: "writable",
        ensureIsManager: "writable",
      },
    },
    plugins: {
      "@stylistic": stylistic,
    },
    rules: {
      "no-undef": "off",
      // Add custom rules here
    },
  },
];
